### ISSUE TITLE
detecting TCP Fast Open

### ISSUE THREAD

**Issue by sanketplus** [veithen/knetstat#13]
Hey, 

Any plans on detecting TFO sockets? It's kinda new thing and I could not find a way or tool which helps checking if a socket is listening with TFO enabled. 

Thanks!

**Comment by veithen** [comment]
No plans, but pull requests are welcome.

**Comment by sanketplus** [comment]
sure. I will take a look at the code and if it makes sense to me(as I have not worked on kernel module before), I'll be making a PR.
